Update post

diff --git a/post b/post
--- a/post
+++ b/post
@@ -1,6 +1,24 @@
 #!/bin/bash
-## Same for pacman and Arch derivatives 
-#Made to be run as root post basic KDE install. 
+## /* SPDX-FileCopyrightText: 2025 
+# (O) Eihdran L. <hadean-eon-dev@proton.me>
+# (C) Lagan S. <sarbjitsinghsandhu509@gmail.com>
+# Desc: Minimal Post Script for Arch Linux KDE.
+# Made to be run as root post basic KDE install. 
+##  SPDX-License-Identifier: MIT */
+#set -e
+#set -x
+if [ "$(whoami)" != "root" ]; then
+    echo "This script must be run as root. Exiting."
+    exit 1
+fi
+#### Should return "us" "fr" "de" "it" "es" etc 
+# Exit if no TARGET_USER found
+if [ -z "$TARGET_USER" ]; then
+    echo "ERROR: No user with /home directory found. Exiting."
+    exit 1
+fi
+
+#### CONFIG
 TARGET_USER=hadean
 KB_LAYOUT=be
 VARIANT=nodeadkeys
