Update post

diff --git a/post b/post
--- a/post
+++ b/post
@@ -30,11 +30,12 @@ echo ""
 # Confirmation prompt
 read -p "Continue with these settings? (y/N): " -n 1 -r
 echo
-if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-    die "Aborted."
-    exit 1
+if [ "$REPLY" != "y" ] && [ "$REPLY" != "Y" ]; then
+  die "Aborted."
+  exit 1
 fi
 echo ""
+
 
 info "Checking target user..." 
 ## Check the target user is correct
